### PR TITLE
iOS target

### PR DESCRIPTION
**Pull request by joostlubach**
Hi there,

I've added an iOS target.

### CODE REVIEW

**Comment by kylef** [comment]
Hi @yoazt, thanks for the pull request. But there is already a target that's capable of building iOS. See the CI: https://github.com/QueryKit/QueryKit/blob/master/.travis.yml#L6

```
$ xcodebuild -project QueryKit.xcodeproj -scheme QueryKit test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
```

**Comment by yoazt** [comment]
Hi Kyle,

Sorry I forgot to specify it explicitly but this one has a shared scheme so
it's compatible with Carthage. If I use your latest version, Carthage
doesn't build for the iOS platform.

Thanks!

**Comment by kylef** [comment]
0.12.1 (https://github.com/QueryKit/QueryKit/commit/ad0d34570e0dbb6976ea9a0d2b5c5f837bc38698) should have added support to Carthage. Can you provide the actual error message you're seeing?

**Comment by kylef** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
