### PR TITLE
Don't hard-code pointer size.

### LINKED ISSUE #29: unsafeBitCast results in a EXC_BAD_INSTRUCTION on non 64 Bit device
When I execute my QueryKit app on a non 64 bit device I get a EXC_BAD_INSTRUCTION at following code sample:

    var qs = Sensor.queryset(managedObjectContext).filter(
        Sensor.attributes.sensorStarted != 0 &&
        Sensor.attributes.sensorStopped == 0)

In the QueryKit source code attributes.swift in line 50

            let value = unsafeBitCast(value, Optional<NSObject>.self)

I get this error: `fatal error: can't unsafeBitCast between types of different sizes`
Everything works as expected on 64 bit devices.

### PR DESCRIPTION
**Pull request by neonichu**
Fixes #29

### CODE REVIEW

**Comment by AliSoftware** [comment]
@kylef @neonichu Just had an idea that's worth trying: wrapping `T` in an `Optional` (even if it's an optional already) then use `flatMap` to reduce levels of optionals to 1:

```
public struct Attribute<T : AnyObject> {
    func expressionForValue(value:T) -> NSExpression {
        // Cleaner implementation?
        let optValue = Optional<T>(value).flatMap{$0}
        
        if let value = optValue {
            return NSExpression(forConstantValue: value)
        }
    
        return NSExpression(forConstantValue: NSNull())
    }
}
```

Would this solve your issue?

**Comment by neonichu** [comment]
@AliSoftware doesn't seem to work, either:

```
.../QueryKit/Attribute.swift:42:20: Cannot find an initializer for type 'NSExpression' that accepts an argument list of type '(forConstantValue: T)'
```

in the `if let` case.

**Comment by AliSoftware** [comment]
Yeah did more tests and unfortunately we're down to the same old problems again.

Did a lot of tests with some `func optionalize<U>(v: U) -> U? { return U?(v) }` + `func optionalize<U>(v: U?) -> U? { return v}` override too.  
Those works outside of the `struct Attribute<T>` and the proper override is used in that case…
But inside `Attribute<String?>` then we got `T=String?` which is seen by the compiler as an un-dissociable unit `T`…

The problem is that the compiler's type-resolver backtracking algorithm will always try to resolve everything against `T` as a whole, not against its decomposed version `String?` seen itself as a composed type. If it were about to solve it against the decomposed type, it would have allowed it to match `U=String` then match `optionalize<String>(String?) -> String?` and solve our problem, but it can't match `U=String` and only `U=T=String?` as `T` is not decomposed at type-resolution time in that context :sad:

**Comment by neonichu** [comment]
I wonder if this is worth a radar? :satellite:

**Pull request merged**
